Update libc++abi's testit_android
Change-Id: I099d832dce893affc0ef9587b5f4ece284af04a0

diff --git a/sources/cxx-stl/llvm-libc++abi/libcxxabi/test/testit_android b/sources/cxx-stl/llvm-libc++abi/libcxxabi/test/testit_android
--- a/sources/cxx-stl/llvm-libc++abi/libcxxabi/test/testit_android
+++ b/sources/cxx-stl/llvm-libc++abi/libcxxabi/test/testit_android
@@ -26,8 +26,6 @@ cd ..
 LIBCXX_ROOT=`pwd`/../../llvm-libc++/libcxx
 cd $origpath
 
-ANDROID_SUPPORT=$(cd "$LIBCXX_ROOT"/../../../android/support && pwd)
-
 VERBOSE=1
 
 run () {
@@ -79,6 +77,7 @@ TARGET_ABI=
 TARGET_ARCH=
 TARGET_PATH=/data/local/tmp/libcxx
 CXX=
+WITH_COMPILER_RT=
 for OPT; do
   case $OPT in
     --help|-?)
@@ -90,11 +89,17 @@ for OPT; do
     --static)
       DO_STATIC=true
       ;;
+    --shared)
+      DO_STATIC=
+      ;;
     --cxx=*)
       CXX=${OPT##--cxx=}
       ;;
     --verbose)
       VERBOSE=$(( $VERBOSE + 1 ))
+      ;;
+    --with-compiler-rt)
+      WITH_COMPILER_RT=yes
       ;;
     -*)
       echo "Unknown option: $OPT. See --help."
@@ -172,20 +177,22 @@ for LIB in libc++_static.a libc++_shared.so; do
 done
 
 LIBCOMPILER_RT_LIBS=$(cd "$LIBCXX_ROOT"/../../../android/compiler-rt && pwd)/libs/$TARGET_ABI
-for LIB in libcompiler_rt_static.a libcompiler_rt_shared.so; do
-  if [ ! -f "$LIBCOMPILER_RT_LIBS/$LIB" ]; then
-    echo "ERROR: Missing prebuilt library: $LIBCOMPILER_RT_LIBS/$LIB"
-    echo "Please run: build/tools/build-compiler-rt.sh --ndk-dir=$NDK \
+if [ "$WITH_COMPILER_RT" = "yes" ]; then
+  for LIB in libcompiler_rt_static.a libcompiler_rt_shared.so; do
+    if [ ! -f "$LIBCOMPILER_RT_LIBS/$LIB" ]; then
+      echo "ERROR: Missing prebuilt library: $LIBCOMPILER_RT_LIBS/$LIB"
+      echo "Please run: build/tools/build-compiler-rt.sh --ndk-dir=$NDK \
 --src-dir=/tmp/ndk-$USER/src/llvm-3.3/compiler-rt --llvm-version=3.3"
-    exit 1
-  fi
-done
+      exit 1
+    fi
+  done
+fi
 
 # Check or detect C++ toolchain.
 TOOLCHAIN_CFLAGS=
 TOOLCHAIN_LDFLAGS=
 if [ -z "$TOOLCHAIN_PREFIX" ]; then
-  # Compute 
+  # Compute
   case $TARGET_ABI in
     armeabi)
       TOOLCHAIN_PREFIX=arm-linux-androideabi
@@ -196,6 +203,11 @@ if [ -z "$TOOLCHAIN_PREFIX" ]; then
       TOOLCHAIN_PREFIX=arm-linux-androideabi
       TOOLCHAIN_CFLAGS="-march=armv7-a -mthumb -mfpu=vfpv3-d16"
       TOOLCHAIN_LDFLAGS="-march=armv7-a -mthumb -Wl,--fix-cortex-a8"
+      ;;
+    armeabi-v7a-hard)
+      TOOLCHAIN_PREFIX=arm-linux-androideabi
+      TOOLCHAIN_CFLAGS="-march=armv7-a -mthumb -mfpu=vfpv3-d16 -mhard-float -D_NDK_MATH_NO_SOFTFP=1"
+      TOOLCHAIN_LDFLAGS="-march=armv7-a -mthumb -Wl,--fix-cortex-a8 -Wl,--no-warn-mismatch -lm_hard"
       ;;
     x86)
       TOOLCHAIN_PREFIX=i686-linux-android
@@ -238,25 +250,22 @@ function version_ge {
 if [ -z "$OPTIONS" ]
 then
   OPTIONS="-std=c++11 -g -funwind-tables"
+  # Note that some tests use assert() to check condition but -O2 defines assert() to nothing,
+  # unless we specify -UNDEBUG to bring assert() back.
+  # But currently adding -UNDEBUG crashes both clang3.4 and clang3.3 for test
+  # like libcxx/test/atomics/atomics.types.generic/address.pass.cpp.  Define -UNDEBUG
+  # only when we are not using clang.  ToDo
+  if [ "$CXX" = "${CXX%%*clang++*}" ] ; then
+    OPTIONS="$OPTIONS -UNDEBUG"
+  fi
   if version_ge "$LLVM_VERSION" "3.4"; then
     OPTIONS="${OPTIONS} -mllvm -arm-enable-ehabi-descriptors -mllvm -arm-enable-ehabi"
   fi
 fi
 OPTIONS="$OPTIONS $TOOLCHAIN_CFLAGS $TOOLCHAIN_LDFLAGS"
 OPTIONS="$OPTIONS -I$LIBCXX_ROOT/test/support"
-# llvm-libc++/libcxx/test/lit.cfg line #294 defineds the following for testing on Linux
+# llvm-libc++/libcxx/test/lit.cfg line #278 defineds the following for testing only on Linux
 OPTIONS="$OPTIONS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS"
-
-if [ -z "$HEADER_INCLUDE" ]
-then
-  HEADER_INCLUDE="-I$LIBCXX_ROOT/include -I$ANDROID_SUPPORT/include"
-fi
-
-if [ -z "$SOURCE_LIB" ]
-then
-  SOURCE_LIB="-L$LIBCXX_LIBS"
-fi
-SOURCE_LIB="$SOURCE_LIB -L$LIBCOMPILER_RT_LIBS"
 
 if [ -z "$ADB" ]
 then
@@ -264,9 +273,11 @@ then
 fi
 
 # Run a shell command through ADB, return its status.
+# Variable ERR contains output if $RET is non-zero
 adb_shell () {
   # We need a temporary file to store the output of our command
-  local CMD_OUT RET OUTPUT
+  local CMD_OUT RET
+  ERR=
   CMD_OUT=$(mktemp /tmp/testit_android-cmdout-XXXXXX)
   # Run the command, while storing the standard output to CMD_OUT
   # and appending the exit code as the last line.
@@ -278,10 +289,13 @@ adb_shell () {
   RET=$(sed -e '$!d' $CMD_OUT)
   # Get output, which corresponds to everything except the last line
   OUT=$(sed -e '$d' $CMD_OUT)
-  rm -f $CMD_OUT
+  if [ "$RET" != "0" ]; then
+    ERR=$OUT
+  fi
   if [ "$VERBOSE" -gt 2 ]; then
     printf "%s" "$OUT"
   fi
+  rm -f $CMD_OUT
   return $RET
 }
 
@@ -298,12 +312,29 @@ adb_push () {
 adb_run () {
   local EXECUTABLE=$1
   local EXECUTABLE_BASENAME=$(basename "$EXECUTABLE")
-  run2 $ADB push $EXECUTABLE $TARGET_PATH/$EXECUTABLE_BASENAME 2>/dev/null &&
-  local TRACE_EXPORTS=""
-  if [ -n "${ENABLE_TRACE}" ]; then
-    TRACE_EXPORTS="export LIBUNWIND_PRINT_APIS=1; export LIBUNWIND_PRINT_UNWINDING=1;"
+  run2 $ADB push $EXECUTABLE $TARGET_PATH/$EXECUTABLE_BASENAME 2>/dev/null
+  if [ "$?" != 0 ]; then
+    return 1;
   fi
-  adb_shell "${TRACE_EXPORTS} LD_LIBRARY_PATH=$TARGET_PATH; cd $TARGET_PATH; ./$EXECUTABLE_BASENAME"
+  # Retry up to 10 times if fail is due to "Text file busy"
+  for i in 1 2 3 4 5 6 7 8 9 10; do
+    adb_shell "LD_LIBRARY_PATH=$TARGET_PATH; cd $TARGET_PATH; ./$EXECUTABLE_BASENAME"
+    if [ "$?" = "0" ]; then
+      return 0
+    fi
+    if ! $(echo $ERR | grep -iq "Text file busy"); then
+      if [ "$i" != "1" ]; then
+        # Dump error message to help diagnostics
+        echo "ERR=$ERR"
+      fi
+      break;
+    fi
+    echo "Text file busy.  Re-try $i"
+    sleep 1
+    run2 $ADB push $EXECUTABLE $TARGET_PATH/$EXECUTABLE_BASENAME 2>/dev/null
+    sleep 2  # try again
+  done
+  return 1
 }
 
 adb_shell "rm -rf $TARGET_PATH"
@@ -311,17 +342,29 @@ adb_shell "mkdir -p $TARGET_PATH"
 
 if [ "$DO_STATIC" ]; then
   # Statically link to ensure the executable can be run easily through ADB
-  LIBS="-lc++_static -lcompiler_rt_static -latomic"
+  # Note that in standalone toolchain libc++_static is renamed to libstdc++, and
+  # compiler adds -lstdc++ implicitly
+  if [ "$WITH_COMPILER_RT" = "yes" ]; then
+    LIBS="-lcompiler_rt_static -latomic"
+  else
+    LIBS="-latomic"
+  fi
 else
   run2 $ADB push $LIBCXX_LIBS/libc++_shared.so $TARGET_PATH 2>/dev/null
   if [ $? != 0 ]; then
     echo "ERROR: Can't push shared libc++ to target device!"
     exit 1
   fi
-  run2 $ADB push $LIBCOMPILER_RT_LIBS/libcompiler_rt_shared.so $TARGET_PATH 2>/dev/null
-  if [ $? != 0 ]; then
-    echo "ERROR: Can't push shared libcompiler_rt to target device!"
-    exit 1
+  if [ "$WITH_COMPILER_RT" = "yes" ]; then
+    run2 $ADB push $LIBCOMPILER_RT_LIBS/libcompiler_rt_shared.so $TARGET_PATH 2>/dev/null
+    if [ $? != 0 ]; then
+      echo "ERROR: Can't push shared libcompiler_rt to target device!"
+      exit 1
+    fi
+    LIBS="-lc++_shared -lcompiler_rt_shared -latomic"
+    #LIBS="-nodefaultlibs -lc++_shared -lcompiler_rt_shared -latomic -ldl -lc -lm"
+  else
+    LIBS="-lc++_shared -latomic"
   fi
   LIBS="-nodefaultlibs -lc++_shared -lcompiler_rt_shared -latomic -ldl -lc -lm"
 fi
@@ -343,12 +386,25 @@ UNIMPLEMENTED=0
 IMPLEMENTED_FAIL=0
 IMPLEMENTED_PASS=0
 
+# Run tests in current directory, recursively
+#
+# Note that file path containing EQ are symlink to the existing tests whose path contain '=',
+# to workaround an issue in ndk-build which doesn't handle LOCAL_SRC_FILES with '='.
+# See tests/device/test-libc++-static-full/jni/Android.mk  We need to filter out path containing
+# EQ such that we don't run same tests twice
+#
+# An alternative is to do "find . -type f", but this doesn't work in NDK windows package
+# where zip turns symlink into physical file it points to.
+#
+# We also sort the test to make the test report comparable to previous test
+#
+
 afunc() {
 	fail=0
 	pass=0
 	if (ls ${TEST_PREFIX}*fail.cpp > /dev/null 2>&1)
 	then
-		for FILE in $(ls ${TEST_PREFIX}*fail.cpp); do
+		for FILE in $(ls ${TEST_PREFIX}*fail.cpp | tr ' ' '\n' | grep -v EQ | sort); do
 			if run $CC $OPTIONS $HEADER_INCLUDE $SOURCE_LIB $FILE $LIBS -o $TEST_EXE > /dev/null 2>&1
 			then
 				rm $TEST_EXE
@@ -364,8 +420,8 @@ afunc() {
 	then
 		if (ls *.dat > /dev/null 2>&1)
 		then
-			adb_shell "rm $TARGET_PATH/*.dat"
-			for FILE in $(ls *.dat); do
+			adb_shell "rm -f $TARGET_PATH/*.dat"
+			for FILE in $(ls *.dat | tr ' ' '\n' | grep -v EQ | sort); do
 	                      if [ "$VERBOSE" -gt 1 ]; then
 	                          echo "Pushing data: " $FILE
 			      fi
@@ -375,7 +431,7 @@ afunc() {
 	                      fi
 			done
 		fi
-		for FILE in $(ls ${TEST_PREFIX}*.cpp); do
+		for FILE in $(ls ${TEST_PREFIX}*.cpp | tr ' ' '\n' | grep -v EQ | sort); do
                       if [ "$VERBOSE" -gt 1 ]; then
                           echo "Running test: " $FILE
                       fi
@@ -422,7 +478,7 @@ afunc() {
 	FAIL=$(($FAIL+$fail))
 	PASS=$(($PASS+$pass))
 
-	for FILE in *
+	for FILE in $(ls | tr ' ' '\n' | grep -v EQ | sort)
 	do
 		if [ -d "$FILE" ];
 		then
